### ISSUE TITLE
Error using Docker on seperate linux system

### ISSUE THREAD

**Issue by ozdeadmeat** [funkyfranky/FunkMan#11]
I am using a separate linux system in the same network as the overhead for using Windows Docker is enormous. I am getting the following error. I can define an image folder but I didnt see anything about that in the docker exec.

Here is my Compose file

version: "3.3"
services:
  funkman:
      restart: always
      image: funkyfranky/funkman
      container_name: funkman
      environment:
          - FUNKMAN_CHANNELID_AIRBOSS=<REDACTED>
          #- FUNKMAN_CHANNELID_RANGE=1006216842509041786
          #- FUNKMAN_CHANNELID_MAIN=1006216842509041786
          - FUNKMAN_DISCORD_TOKEN=<REDACTED>
      ports:
          - '10042:10042/udp'
      networks:
      - funkman
networks:
  funkman:
    name: funkman

Log Error below

Init FunkPlot: Reading images from /Funky/funkpics/...
Hello, my name is FunkMan. I'm at your service!
Reading config file ./FunkMan.ini
------------------------------------
Config parameters:
Debug level     = 1
Host            = 0.0.0.0
Port            = 10042
Token (5 chars) = MTI3...
Channel Main    = None
Channel Range   = None
Channel Airboss = 1255705388733435955
Image Path      = /Funky/funkpics/
------------------------------------
Init FunkPlot: Reading images from /Funky/funkpics/...
Traceback (most recent call last):
  File "/Funky/./FunkMan.py", line 13, in <module>
    fman=FunkMan()
  File "/usr/local/lib/python3.10/site-packages/funkman/funkman.py", line 49, in __init__
    self.funkbot=FunkBot(self.token, self.channelIDmain, ImagePath=self.imagePath, DebugLevel=self.debugLevel)
  File "/usr/local/lib/python3.10/site-packages/funkman/funkbot/funkbot.py", line 30, in __init__
    self.channelID=int(ChannelID)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by ozdeadmeat** [comment]
Updated the compose file with and got the same error.

version: "3.3"
services:
  funkman:
      restart: always
      image: funkyfranky/funkman
      container_name: funkman
      environment:
          - FUNKMAN_CHANNELID_AIRBOSS=
          #- FUNKMAN_CHANNELID_RANGE=
          #- FUNKMAN_CHANNELID_MAIN=
          - FUNKMAN_DISCORD_TOKEN=
      ports:
          - '10042:10042/udp'
      networks:
      - funkman
      volumes:
      - funkman-pics:/Funky/funkpics # Disk Location where images are stored.
networks:
  funkman:
    name: funkman
volumes:
  funkman-pics:
    name: funkman-pics

**Comment by ozdeadmeat** [comment]
Compose works, but for some reason Github's comment system is dogshit for formatting.

**Comment by funkyfranky** [comment]
I just checked the error line and it comes because you do not specify an ID for the main channel. This cannot be None. 
The AIRBOSS and RANGE channels are optional but not the main channel.
