### ISSUE TITLE
Bot permissions request 

### ISSUE THREAD

**Issue by lonewolfnight** [funkyfranky/FunkMan#4]
Although there are plenty of guides on how to create a BOT. Can you include in the README the permission levels that are needed?

**Comment by lonewolfnight** [comment]
[2023-01-25 15:25:23] [ERROR   ] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 409, in _run_event
    await coro(*args, **kwargs)
  File "C:\Program Files\FunkMan\funkman\funkbot\funkbot.py", line 59, in on_ready
    await self.SendMessage("FunkBot reporting for duty!", self.channelID)
  File "C:\Program Files\FunkMan\funkman\funkbot\funkbot.py", line 103, in SendMessage
    await channel.send(Text)
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\discord\abc.py", line 1538, in send
    data = await state.http.send_message(channel.id, params=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

**Comment by funkyfranky** [comment]
I have added a line to check the bot permissions if that error appears. Not sure myself, which permissions are necessary.
