### ISSUE TITLE
Trapsheet Issues - AOA

### ISSUE THREAD

**Issue by Rolln-dev** [funkyfranky/FunkMan#5]
Getting this error once in a while.   It seems to happen when a pilot gets a WO call and looks like it has something to do with AOA in the `np.min(AoA)` call.

```python
        # AoA values. We skip the last values before the landing.
        AoA=AOA[:-num_aoa]

        # Get AC specific AoA values.
        AoAmin, AoAopt, AoAmax=self._GetAoA(actype)

        # Plot limit.
        xmax=ax.get_xlim()[1]

        # Plot AoA limits.
        ax.plot([0,xmax], [AoAmax,AoAmax], 'r--', linewidth=1.2, alpha=0.6)
        ax.plot([0,xmax], [AoAmin,AoAmin], 'r--', linewidth=1.2, alpha=0.6)
        ax.plot([0,xmax], [AoAopt,AoAopt], 'g--', linewidth=1.2, alpha=0.6)

        AoAmin=min(AoAmin, np.min(AoA))
        AoAmax=max(AoAmax, np.max(AoA))
```

We are using DSCServerBot, but that shouldn't be a contributing factor. The FunkMan code has not been altered in any way.

```Traceback (most recent call last):
  File "C:\vnao\DCSServerBot\core\listener.py", line 24, in processEvent
    return await getattr(self, data['command'])(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\plugins\funkman\listener.py", line 126, in moose_lso_grade
    fig, _ = self.funkplot.PlotTrapSheet(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\../FunkMan\funkman\funkplot\funkplot.py", line 593, in PlotTrapSheet
    AoAmin=min(AoAmin, np.min(AoA))
                       ^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amin
  File "C:\vnao\DCSServerBot\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by Rolln-dev** [comment]
I think it might be when a WO grade with LIG detail.

**Comment by funkyfranky** [comment]
That would make sense. If you get a LIG grade, the AoA array is probably empty and the min function crashes.

**Comment by Rolln-dev** [comment]
And it may have been happening as well when they got a WOP but can't confirm. So I think your idea is on the mark.

**Comment by Rolln-dev** [comment]
Just some debug messaging I added.

A trap that does not error out:
```cmd
funkplot: AoA:[4.1  4.2  4.26 4.21 4.1  3.62 3.12 3.21 4.33 4.98 4.24 3.48 4.09 4.66
 4.38 2.79 1.23 1.   1.94 2.85 2.41 2.68 4.13 4.41 3.26 2.62 2.44 2.
 2.62 3.63 3.91 3.87 3.89 3.69 3.52 3.57 3.5  3.22 2.48 2.32 3.09 3.34
 3.08 3.16 3.13 2.77 2.63 2.7  2.9  2.63 2.19 2.48 2.7  2.59 2.49 2.38
 2.34 2.42 3.   3.83 3.92 3.76 3.45 3.02 2.81 1.9  0.69 0.5  0.89 1.19
 1.92 2.9  3.24 3.19 3.35 3.56 3.63 3.73 3.84 3.9  3.84 3.32 2.93 2.24
 1.29 1.11 1.24 1.17 1.58 2.92 3.6  3.01 2.51 2.76 3.19 3.72 3.83 3.79
 3.55 2.29 1.01 1.32 1.72 1.21 2.14 3.53 3.5  3.2  2.74 2.46 2.41 2.3
 2.23 2.4  3.13 3.29 3.05 3.04 3.12 3.19 3.06 2.34 2.3  2.64 2.68 2.48
 2.5  2.85 2.99 2.77 2.64 2.99 2.81 2.28 2.23 2.75 3.24 2.83 3.11 3.68
 3.44 3.47 3.79 3.9  3.95 3.95 3.28 2.19 1.85 2.47 3.77 4.05 2.94 1.9
 1.46 1.13 0.76 0.95 1.78 2.04]  AoAmin:7.4  AoAopt:8.1  AoAmax:8.8
 ```
 And this is a trap that throws the error:
 ```cmd
funkplot: AoA:[]  AoAmin:9.5  AoAopt:10.0  AoAmax:10.5
2023-02-22 19:27:35.581 ERROR   MainThread      zero-size array to reduction operation minimum which has no identity
Traceback (most recent call last):
  File "C:\vnao\DCSServerBot\core\listener.py", line 24, in processEvent
    return await getattr(self, data['command'])(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\plugins\funkman\listener.py", line 126, in moose_lso_grade
    fig, _ = self.funkplot.PlotTrapSheet(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\../FunkMan\funkman\funkplot\funkplot.py", line 597, in PlotTrapSheet
    AoAmin=min(AoAmin, np.min(AoA))
                       ^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in amin
  File "C:\vnao\DCSServerBot\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\vnao\DCSServerBot\venv\Lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ```

**Comment by Rolln-dev** [comment]
Thank you, running it now.

**Comment by funkyfranky** [comment]
Can we close this @Rolln-dev ?

**Comment by Rolln-dev** [comment]
> Can we close this @Rolln-dev ?

Sorry, missed this.  Yes, can be closed.
