### ISSUE TITLE
no scores on strafe passes following update from 0.6.5 to 0.6.6

### ISSUE THREAD

**Issue by hbjonsson** [funkyfranky/FunkMan#8]
Getting no scores on strafe passes following update from 0.6.5 to 0.6.6

Get these errors here in the command prompt:

```
Exception` occurred during processing of request from ('127.0.0.1', 57138)
Traceback (most recent call last):
  File "C:\Users\Games\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Games\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Games\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Games\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\FUNKMAN\funkman\funksock\funksock.py", line 44, in handle
    self.server.EvalData(table)
  File "C:\FUNKMAN\funkman\funksock\funksock.py", line 149, in EvalData
    fig, ax=self.funkplot.PlotStrafeRun(table)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FUNKMAN\funkman\funkplot\funkplot.py", line 346, in PlotStrafeRun
    ab = AnnotationBbox(offsetbox,
                        ^^^^^^^^^
UnboundLocalError: cannot access local variable 'x' where it is not associated with a value
```

**Comment by funkyfranky** [comment]
Should hopefully be fixed now in release v0.7.3
